export interface ConsoleLaneConnection {
  activation: string;
  allowedCapabilities: string[];
  auditMode: "required";
  connectionMode: string;
  consoleConnector: string;
  entrypoint: string;
  lane: string;
  mcpTransport: "http";
  requiredHeaders: string[];
  requiredSecrets: string[];
  status: string;
}

export interface SkippedConsoleLane {
  lane: string;
  reason: string;
}

export const CONSOLE_LANE_AUTHORITY = {
  account: "5b94eedaff8fb3ccaa1b607f57963e10",
  zone: "ellis-aegis.us",
  worker: "mj-edge",
  entrypoints: [
    "https://mj.ellis-aegis.us",
    "https://mcp.ellis-aegis.us",
    "https://codex.ellis-aegis.us",
  ],
} as const;

const REQUIRED_HEADERS = [
  "x-tenant-id",
  "x-request-id",
  "x-policy-version",
  "x-operator-capability",
] as const;

function lane(input: Omit<ConsoleLaneConnection, "auditMode" | "mcpTransport" | "requiredHeaders">): ConsoleLaneConnection {
  return {
    ...input,
    auditMode: "required",
    mcpTransport: "http",
    requiredHeaders: [...REQUIRED_HEADERS],
  };
}

export const CONSOLE_LANES: ConsoleLaneConnection[] = [
  lane({
    activation: "Connect Codex to the remote MJ MCP endpoint with operator headers.",
    allowedCapabilities: ["mcp.admin", "script.run", "cloud.ops", "forensic.read"],
    connectionMode: "remote_mcp_operator",
    consoleConnector: "Codex",
    entrypoint: "https://codex.ellis-aegis.us/mcp",
    lane: "mj-codex",
    requiredSecrets: ["OPERATOR_TOKEN"],
    status: "ready_for_operator_token",
  }),
  lane({
    activation: "Use the in-app Browser connector for dashboard validation and smoke screenshots.",
    allowedCapabilities: ["mcp.admin", "forensic.read"],
    connectionMode: "local_console_connector",
    consoleConnector: "Browser",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-browser",
    requiredSecrets: ["OPERATOR_TOKEN"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Install/use Chrome automation only for approved profile-backed browser work.",
    allowedCapabilities: ["mcp.admin", "forensic.read"],
    connectionMode: "optional_local_plugin",
    consoleConnector: "chrome",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-chrome",
    requiredSecrets: ["OPERATOR_TOKEN"],
    status: "connector_install_required",
  }),
  lane({
    activation: "Use Superpowers for plan, TDD, verification, and handoff discipline.",
    allowedCapabilities: ["mcp.admin", "forensic.read"],
    connectionMode: "local_console_connector",
    consoleConnector: "Superpowers",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-superpowers",
    requiredSecrets: ["OPERATOR_TOKEN"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "GitHub Actions remains the enterprise deploy gate; GitHub App/OIDC handles repo workflows.",
    allowedCapabilities: ["repo.read", "pr.comment", "workflow.dispatch"],
    connectionMode: "github_app_or_oidc",
    consoleConnector: "GitHub",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-github",
    requiredSecrets: ["GITHUB_TOKEN or GitHub App credentials"],
    status: "ready_for_app_or_oidc",
  }),
  lane({
    activation: "Cloudflare is the runtime substrate for Workers, D1, R2, KV, queues, zones, WAF, and smoke checks.",
    allowedCapabilities: ["cloud.ops", "security.status", "forensic.read"],
    connectionMode: "cloudflare_api_token",
    consoleConnector: "Cloudflare",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-cloudflare",
    requiredSecrets: ["CF_API_TOKEN", "CF_ACCOUNT_ID", "CF_ZONE_ID_ELLIS", "CF_ZONE_ID_HITCH", "CF_ZONE_ID_KEVIS"],
    status: "ready_for_api_token",
  }),
  lane({
    activation: "Use official OpenAI APIs/connectors for model and agent work without exposing API key values.",
    allowedCapabilities: ["model.route", "tool.call_approved"],
    connectionMode: "api_or_connector",
    consoleConnector: "OpenAI Developers",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-openai",
    requiredSecrets: ["OPENAI_API_KEY or approved OpenAI connector"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Use Figma for design-system and implementation handoffs.",
    allowedCapabilities: ["doc.read", "tool.call_approved"],
    connectionMode: "oauth_connector",
    consoleConnector: "Figma",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-figma",
    requiredSecrets: ["approved Figma connector"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Use the Google family lane for Workspace, Firebase, AI Studio, Gemini, and Vertex operations.",
    allowedCapabilities: ["drive.read_approved", "workspace.action_approved"],
    connectionMode: "oauth_or_service_account",
    consoleConnector: "Google",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-google",
    requiredSecrets: ["GOOGLE_SERVICE_ACCOUNT_JSON or approved OAuth connector"],
    status: "ready_for_oauth_or_service_account",
  }),
  lane({
    activation: "Use Drive, Docs, Sheets, and Slides for document projections and operating artifacts.",
    allowedCapabilities: ["doc.read", "doc.update_approved"],
    connectionMode: "oauth_connector",
    consoleConnector: "Google Drive",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-google-drive",
    requiredSecrets: ["approved Google Drive connector"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Use Calendar for scheduling, prep, and availability projections.",
    allowedCapabilities: ["doc.read", "tool.call_approved"],
    connectionMode: "oauth_connector",
    consoleConnector: "Google Calendar",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-google-calendar",
    requiredSecrets: ["approved Google Calendar connector"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Use Notion for specs, knowledge capture, and implementation planning projections.",
    allowedCapabilities: ["doc.read", "doc.update_approved"],
    connectionMode: "oauth_connector",
    consoleConnector: "Notion",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-notion",
    requiredSecrets: ["NOTION_TOKEN or approved Notion connector"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Use Linear for issue, project, and build-task projections.",
    allowedCapabilities: ["issue.read", "issue.update_approved"],
    connectionMode: "oauth_connector",
    consoleConnector: "Linear",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-linear",
    requiredSecrets: ["LINEAR_API_KEY or approved Linear connector"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Use Gmail for support triage and reply drafts; sends require approval.",
    allowedCapabilities: ["doc.read", "tool.call_approved"],
    connectionMode: "oauth_connector",
    consoleConnector: "Gmail",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-gmail",
    requiredSecrets: ["approved Gmail connector"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Use CircleCI as an auxiliary CI lane; GitHub Actions remains MJ v1 deploy authority.",
    allowedCapabilities: ["forensic.read", "tool.call_approved"],
    connectionMode: "api_or_connector",
    consoleConnector: "CircleCI",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-circleci",
    requiredSecrets: ["CIRCLECI_TOKEN or approved CircleCI connector"],
    status: "ready_for_api_token",
  }),
  lane({
    activation: "Use the iOS build lane for simulator/build/test workflows.",
    allowedCapabilities: ["script.run", "forensic.read"],
    connectionMode: "local_build_connector",
    consoleConnector: "Build iOS Apps",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-build-ios",
    requiredSecrets: ["local Xcode signing access when explicitly approved"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Use the macOS build lane for local app build/test/package workflows.",
    allowedCapabilities: ["script.run", "forensic.read"],
    connectionMode: "local_build_connector",
    consoleConnector: "Build macOS Apps",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-build-macos",
    requiredSecrets: ["local signing/notarization access when explicitly approved"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Use the web lane for MJ dashboard implementation, browser QA, and frontend deployment evidence.",
    allowedCapabilities: ["mcp.admin", "forensic.read"],
    connectionMode: "local_frontend_connector",
    consoleConnector: "Build Web Apps",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-build-web",
    requiredSecrets: ["OPERATOR_TOKEN for deployed dashboard smokes"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Use Network Solutions for domain search and registrar handoff; Cloudflare remains DNS/runtime authority.",
    allowedCapabilities: ["forensic.read", "tool.call_approved"],
    connectionMode: "domain_connector",
    consoleConnector: "Network Solutions",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-network-solutions",
    requiredSecrets: ["approved Network Solutions connector"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Use Codex Security for security scan, validation, threat model, and finding fix review.",
    allowedCapabilities: ["security.status", "forensic.read"],
    connectionMode: "security_connector",
    consoleConnector: "Codex Security",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-codex-security",
    requiredSecrets: ["approved Codex Security connector"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Use Scite for research-backed enterprise, security, and compliance claims.",
    allowedCapabilities: ["doc.read", "forensic.read"],
    connectionMode: "research_connector",
    consoleConnector: "Scite",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-scite",
    requiredSecrets: ["approved Scite connector"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Use Canva for branded design and presentation artifacts.",
    allowedCapabilities: ["doc.read", "tool.call_approved"],
    connectionMode: "design_connector",
    consoleConnector: "Canva",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-canva",
    requiredSecrets: ["approved Canva connector"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Use Supabase for future product database operations, not MJ v1 runtime truth.",
    allowedCapabilities: ["cloud.ops", "forensic.read"],
    connectionMode: "database_connector",
    consoleConnector: "Supabase",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-supabase",
    requiredSecrets: ["approved Supabase connector"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Use Documents for local docx artifacts, render checks, and handoff documents.",
    allowedCapabilities: ["doc.read", "tool.call_approved"],
    connectionMode: "local_artifact_connector",
    consoleConnector: "Documents",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-documents",
    requiredSecrets: ["OPERATOR_TOKEN"],
    status: "ready_for_local_artifact_scope",
  }),
  lane({
    activation: "Use Presentations for deck generation, render verification, and enterprise narratives.",
    allowedCapabilities: ["doc.read", "tool.call_approved"],
    connectionMode: "local_artifact_connector",
    consoleConnector: "Presentations",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-presentations",
    requiredSecrets: ["OPERATOR_TOKEN"],
    status: "ready_for_local_artifact_scope",
  }),
  lane({
    activation: "Use Spreadsheets for evidence tables, billing models, and operational reports.",
    allowedCapabilities: ["doc.read", "forensic.read"],
    connectionMode: "local_artifact_connector",
    consoleConnector: "Spreadsheets",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-spreadsheets",
    requiredSecrets: ["OPERATOR_TOKEN"],
    status: "ready_for_local_artifact_scope",
  }),
  lane({
    activation: "Use Android test lane for emulator QA and performance evidence.",
    allowedCapabilities: ["script.run", "forensic.read"],
    connectionMode: "local_emulator_connector",
    consoleConnector: "Test Android Apps",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-test-android",
    requiredSecrets: ["local Android emulator access"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Use Vercel for preview frontend deployments and status projections.",
    allowedCapabilities: ["cloud.ops", "forensic.read"],
    connectionMode: "api_or_connector",
    consoleConnector: "Vercel",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-vercel",
    requiredSecrets: ["VERCEL_TOKEN or approved Vercel connector"],
    status: "ready_for_connector_scope",
  }),
  lane({
    activation: "Connect Zed as an approved remote MCP operator.",
    allowedCapabilities: ["mcp.admin", "script.run", "forensic.read"],
    connectionMode: "remote_mcp_operator",
    consoleConnector: "Zed",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-zed",
    requiredSecrets: ["OPERATOR_TOKEN"],
    status: "ready_for_operator_token",
  }),
  lane({
    activation: "Connect Cursor as an approved remote MCP operator.",
    allowedCapabilities: ["mcp.admin", "script.run", "forensic.read"],
    connectionMode: "remote_mcp_operator",
    consoleConnector: "Cursor",
    entrypoint: "https://mcp.ellis-aegis.us/mcp",
    lane: "mj-cursor",
    requiredSecrets: ["OPERATOR_TOKEN"],
    status: "ready_for_operator_token",
  }),
  lane({
    activation: "Start the local bridge only for local inference lanes; do not expose it publicly.",
    allowedCapabilities: ["script.run", "forensic.read"],
    connectionMode: "local_bridge",
    consoleConnector: "Local Models",
    entrypoint: "http://127.0.0.1:8789/mcp",
    lane: "mj-local-models",
    requiredSecrets: ["local Ollama models"],
    status: "ready_for_local_bridge",
  }),
];

export const SKIPPED_CONSOLE_LANES: SkippedConsoleLane[] = [
  { lane: "mj-computer", reason: "console plugin or Stratos_Tools application not observed" },
  { lane: "mj-gadget", reason: "console plugin or Stratos_Tools application not observed" },
  { lane: "mj-railway", reason: "console plugin or Stratos_Tools application not observed" },
];
